### ISSUE TITLE
Shape dcat:Dataset

### ISSUE THREAD

**Issue by ghost** [SEMICeu/dcat-ap_shacl#16]
I don't see following properties included:
- dcat:keyword
- dct:identifier
- adms:versionNotes

**Comment by costezki** [comment]
In one of the initial conversations we have decided to record only the absolute minimal constraints. Therefore in current implementation constraints are provided only for the Mandatory properties. 

dcat:keyword [Recommended]
dct:identifier [Optional]
adms:versionNotes [Optional]
