### ISSUE TITLE
older version of SHACL?

### ISSUE THREAD

**Issue by ghost** [SEMICeu/dcat-ap_shacl#17]
I see in the latest proposed recommendation

2017-01-19: Removed sh:predicate in favor of using sh:path only (ISSUE-217).

This SHACL file is still using sh:predicate

**Comment by makxdekkers** [comment]
Also raised by Håvard Mikkelsen Ottestad.

**Comment by makxdekkers** [comment]
Also raised by Håvard Mikkelsen Ottestad:

2017-02-02: Renamed sh:shape to sh:node, limited its range to node shapes (ISSUE-221)

**Comment by makxdekkers** [comment]
Also raised by Simon Dutkowski:

The definitions are not well aligned with the latest shacl documentation.  E.g. sh:predicate is deprecated (Issue 217), or sh:Shape is now renamed to sh:NodeShape and sh:Shape is now formerly sh:Constraint

**Comment by costezki** [comment]
* added the new implementation into ./shacl-latest
* renamed ./shacl into ./shacl-201608 
* updated readme.md

related to #28
