### ISSUE TITLE
Use of sh:hasValue

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#18]
Raised by Håvard Mikkelsen Ottestad:

The way GeoNamesRestriction etc. are modelled with sh:hasValue won’t work (AFAIK). It’ll just force one of your frequencies to be the node <http://publications.europa.eu/resource/authority/frequency>

**Comment by addragan** [comment]
Proposed resolution: Replace the use of sh:hasValue with a node.

**Comment by bertvannuffelen** [comment]
closed because of archiving
