### ISSUE TITLE
sh:Violation of sh:Warning

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#19]
Raised by Håvard Mikkelsen Ottestad:

Everything is sh:Violation. I used sh:Warning for things that were optional/recommended, for instance with minCount 1 for dcat:distribution. This approach may not be the best though.

**Comment by costezki** [comment]
Currently only the Mandatory constraints are recorded as Violations. Optional and Recommended constraints will be added in the next iteration of this work.
