### ISSUE TITLE
Handling of external resources

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#20]
Raised by Håvard Mikkelsen Ottestad:

How are you going to handle external resources in general, for instance for licenses? I have not found a good way of handling this, and ended up loading in a bunch of external rdf files so that the user can reference any resources in those files.

**Comment by costezki** [comment]
In the team meeting it was decided to avoid checking the correctness of the external resources.  No type check and not instantiation check is performed any longer.  Hence, no no need to load any of the external resources for validating current DCAT-AP.
