### ISSUE TITLE
Limiting number of prefLabels

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#21]
Raised by Håvard Mikkelsen Ottestad:

Another rule I’ve looked at is limiting the number of prefLabels. By design you shouldn’t have two prefLabels unless they have different languages, but you can have a prefLabel with a language and one without at the same time. This can be done by using a combination of sh:uniqueLang and maxCount. I discussed this on the SHACL mailing lists and got two solutions (that very rather complicated): https://lists.w3.org/Archives/Public/public-rdf-shapes/2017Jun/0000.html https://lists.w3.org/Archives/Public/public-rdf-shapes/2017May/0042.html

**Comment by costezki** [comment]
Thank you for the suggestion. Checks such as skos:prefLabel are important and therefore shall be properly treated in a specialized SKOS-AP. Please further refer to [SKOS-AP-EU](http://publications.europa.eu/mdr/application-profile/index.html) where the skos:prefLabel constraints are defined/hadled for skos:Concept class.
