### ISSUE TITLE
Publisher defined as skos:Concept?

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#22]
Raised by Martín Álvarez Espinar:

In dcat-ap-mdr-vocabularies.shapes.ttl, 
dcat:Catalog and dcat:Dataset publishers are considered as IRI skos:Concepts. In this case I suppose all the publishers are listed in the Corporate body NAL, right? If not, it sounds weird the class restriction (skos:Concept) and the nodetype (that should be sh:BlankNodeOrIRI).

**Comment by barthanssens** [comment]
It's a bit weird indeed, but I guess it originates from the usage note of DCAT-AP 1.1 itself ("The Corporate bodies NAL must be used for European institutions and a small set of international organisations. In case of other types of organisations, national, regional or local vocabularies should be used)

Note "vocabularies" (seems to imply to use SKOS), so perhaps this should be changed in the next DCAT-AP revision (organization / registered organization makes more sense IMHO)

**Comment by makxdekkers** [comment]
Bart, the issue is that the terms in the Corporate Body NAL are declared to be skos:Concepts. Indeed, it would be strange not to allow instances of the class org:Organization to be the object of a dct:publisher assertion.

**Comment by costezki** [comment]
In the main dcat file (dcat-ap.shapes.ttl) no more constraints are defined on external resources - only sh:isIRI check is left. 

All constraints related to controlled vocabularies have been moved to dcat-ap-mdr-vocabularies.shapes.ttl.
