### ISSUE TITLE
Importing external vocabularies

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#23]
Raised by Paul Hermans:
In the OWL/SHACL all used external vocabs are imported which is good.
However some of those imported ones use other vocabs without importing those (e.g. dcat itself).
It uses e.g. classes from http://purl.org/dc/dcmitype/ but without importing.
It might be an option to import these second line vocabs in the application profile vocab itself.
This shows up nicer in some IDE’s.

**Comment by costezki** [comment]
Transitive import closure is implementation dependent and thus does not concern current work. When It comes to import of external resources - they are optional now for validation with the main dcat-ap module. In principle, loading external models/ontologies is not needed. (related to #24)

It is possible to test whether the data comply with a the set of mdr-vocabularies; to do so it is necessary to load the required vocabularies and the dcat-ap-mdr-vocabularies.shapes.ttl.
