### ISSUE TITLE
vCard vocabulary

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/dcat-ap_shacl#24]
Raised by Paul Hermans:
The vcard:Kind class is used, but in TopBraid Composer the vCard ontology loaded is still the previous one where vCard:Kind doesn’t exist.
This is related to the fact, as you probably know, that vCard is being substantially refactored, but still using the same ns identifier.
I don’t have wisdom on this one, but it can be very confusing.

**Comment by barthanssens** [comment]
Isn't TopBraid using Jena ? I've contributed VCARD4 to Jena and RDF4j, so if Topbraid would upgrade to a newer version (Jena 3.3.0 IIRC), it may help to solve this issue

**Comment by costezki** [comment]
this is a TopBraid issue. One would need to select the source of the loaded/imported ontology. Currently TopBraid provides a default set of common ontologies that have been slightly curated and adapted. 
(related to #23)
