### ISSUE TITLE
schema:startDate minCount

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/dcat-ap_shacl#25]
In dcat-ap.shapes.ttl (line 138) minCount is 1 for startDate, so that would mean that a start date is always mandatory ?

Which makes sense, but DCAT-AP 1.1 spec itself allows a cardinality of 0..1  ("4.11 Period of Time"), so I'd suggest to remove the minCount (and/or take this into account for the next DCAT-AP revision)

**Comment by makxdekkers** [comment]
Bart, both startDate and endDate have cardinality of 0..1 to allow for 'open' ranges, i.e. situations where there is no (known) start date but only an end date and where there is a start date but no end date. It is likely that situations with only start date (e.g. datasets where data is still being added) will be more common then situations with only end data. We can put this on the list for consideration in a future revision of DCAT-AP, maybe based on an analysis of what situations occur in practice.

**Comment by costezki** [comment]
* dct:PeriodOfTime now moved outside the main module. 
* The constraint on minDate is now reduces to comply with the original AP definition
