### ISSUE TITLE
sh:name question

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/dcat-ap_shacl#26]
Very minor remark  (probably due to the software tool being used I guess)

dcat-ap.shapes.ttl line 206 reads "sh:name "Catalog"@en. 
It appears to be the only shape with a sh:name (and also the only literal with a language tag), e.g. adms:Identifier does not use it. Should this be set on the other shapes ? (for viewing / reporting purposes ?) 

On a related note, sh:name is not used on foaf:name (line 651), which seems to be the only sh:property not setting a sh:name

**Comment by costezki** [comment]
* deleted all non essential statements, 
* removed all sh:name, sh:description, (but not sh:message)
