### ISSUE TITLE
vcard:Kind fn mandatory property ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/dcat-ap_shacl#27]
Maybe a vcard:fn should be added to the vcard:Kind shape in dcat-ap.shapes.ttl

The vCard / RDF spec https://www.w3.org/TR/vcard-rdf/ (part 2.3) mentions that fn or hasFN is a (actually, the only) mandatory vCard property

Something like:

sh:property [
      sh:predicate vcard:fn ;
      sh:minCount 1 ;
      sh:nodeKind sh:Literal ;
    ] ;

**Comment by costezki** [comment]
such constraint even if very useful should not be part of the dcat-ap but rather managed in some "standard" vCard-ap SHACL implementation.
