### ISSUE TITLE
implement recommended and optional constraints

### ISSUE THREAD

**Issue by costezki** [SEMICeu/dcat-ap_shacl#29]
- Would be nice in the future :warnings and :info constraints in a separate files [Recommended and optional fields for the future]

**Comment by costezki** [comment]
implementation of Recommended and Optional properties (:warnings and :info) is postponed for the next iteration of this work

**Comment by addragan** [comment]
Proposed resolution: Enhance SHACL distribution by implementing constraints for both Recommended and Optional properties (with :warnings and: info).

**Comment by bertvannuffelen** [comment]
closed because of archiving
