### ISSUE TITLE
to be done 

### ISSUE THREAD

**Issue by costezki** [SEMICeu/dcat-ap_shacl#30]
- Document where to find what (version of old standard and tool support vs new standard )
- Would be nice in the future :warnings and :info constraints in a separate files [Recommended and optional fields for the future]
- Delete all non essential statements 

TODO: by 5th of July
TODO: send a message with the latest version

#16 - check if mandatory or not 

#17 - 

#18 - double check it works 

#20 - make sure they are URIs only; 

#21 - point out that it is for SKOS-AP, thank for suggestion, 

#22 - remove type check and just make sure it is an URI

#23 - comment that it is not a problem

#24 - tool problem 

#25 - relax the min card to 0 for startDate to comply with the specification

#26 - delete all non essential statements, check and remove all sh:name, sh:description, (but not sh:message)

#27 - not implementing, similar to #21

**Comment by costezki** [comment]
Resolved issues
*  #16, #19, #20, #21, #22, #23, #24 , #25 , #25, #26, #27,  #31, #8, #12, #7, #5 
* moved constraints of  non-dcat classes to dcat-ap-mdr-vocabularies.shapes.ttl
* imports no longer needed 
* external resources no longer validated in the main dcat-ap file (only in mdr-vocabulary extension)
* import of external ontologies is not mandatory
* namespace cleanup  (no more tosh and dash namespaces)
* implementation of Recommended and Optional properties (:warnings and :info) is postponed for the next iteration of this work 
* delete all non essential statements, check and remove all sh:name, sh:description, (but not sh:message)
*  ADMS Change TypeVocabulary was never created so no validation constraint for it
* reduced non essential statements to minimum. 
* mandatory class validations moved to an additional module dcat-ap-mandatory-classes.shapes.ttl

**Comment by makxdekkers** [comment]
Thanks. I will take it from here. I'll be in touch if I have any questions.
Makx

Op 4 jul. 2017 6:10 p.m. schreef "Eugeniu Costetchi" <
notifications@github.com>:

**Comment by costezki** [comment]
It is not ready, I'll work on it tomorrow as well.  will submit changes by
the end of the day

**Comment by costezki** [comment]
* tosh and dash namespaces and imports are used by the TopBraid implementations. 

* added the new implementation into ./shacl-latest
* renamed ./shacl into ./shacl-201608
* updated readme.md
