### ISSUE TITLE
shex

### ISSUE THREAD

**Issue by danbri** [SEMICeu/dcat-ap_shacl#32]
Really interesting work! Quick q: did you consider shex at all, or make any investigations into the relative expressivity / usability of these two formats?

**Comment by makxdekkers** [comment]
Personally, I was not aware of ShEx. I just looked at this but it seems to be not as 'authoritative' as the work on SHACL. ShEx is a from a Community Group, SHACL is on W3C Recommendation track which should give more stability. 
So the answer to your question is, no, we have not done such an investigation.

**Comment by costezki** [comment]
Hi Dan, 
  I am well aware of ShEx and that there is a community of users for it just as there is one for SHACL (more recent). After the discussion with Eric in Amsterdam I got the impression that SHACL will cover the needs of ShEx community as well. 

In this first iteration we already maintain two SHACL implementations for DCAT-AP in principle it should be possible to add the ShEx implementation (in the next iterations) if there is a strong need for it. Nevertheless it would probably be nice to conduct first a mini investigation on such a necessity.

**Comment by akuckartz** [comment]
A week ago SHACL became a W3C Recommendation:
https://www.w3.org/standards/techs/shacl

**Comment by danbri** [comment]
The fact that there is both SHACL and ShEx is perhaps unfortunate; my understanding is that the original WG didn't find a complete consensus. The ShEx people left, as did a chair, and the remaining SHACL enthusiasts carried things across the finishing line to W3C REC. If SHACL does the job for your needs, that's great, it seems that both are respectable designs with lots in common and some reasonable design differences too. I'm reminded of the XML Schema WG, which also in some sense was an incubator for Relax NG and Schematron, ideas that eventually ended up specified at Oasis and ISO. It is not necessarily bad for the design space of such languages to be carefully explored in several ways; this is why I was probing here for feedback/conclusions from your work, btw.

Do you have any plans to apply your SHACL experiments to the new DCAT work at W3C? It might be an interesting way to express common (groups of) patterns across 1.0 and 1.x...

**Comment by costezki** [comment]
Hi Dan, thank you for pointing this out. 
I expect that we will perform the same exercise for DCAT 1.1 as for 1.0 and provide parallel sets of formal constraints. This, nevertheless, shall wait until a fairly stable version of DCAT 1.1 and for that I rely @makxdekkers  signal.

**Comment by danbri** [comment]
I wanted to share some experiments from last year, using ShEx with Schema.org's Dataset markup

 * https://goo.gl/gWnC4J

Sample data (Turtle format):

```
PREFIX :       <http://example.org/>
PREFIX so: <http://schema.org/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>

:ds1 so:name "MyDataset"^^so:Text ;
     so:description "A cool dataset"^^so:Text ;
     so:url "http://an.url.com"^^so:URL ;
     so:creator :alice .

:alice a so:Person ;
       so:name "Alice" .
```

Example ShEx:

```
PREFIX :       <http://example.org/>
PREFIX so: <http://schema.org/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

:DataSetShape {
 so:name so:Text ; # // so:recommended ;
 so:description so:Text ? ; #// so:recommended ;
 so:url so:URL ;
 so:creator (@:PersonShape OR @:OrganizationShape) AND 
            @:IdentifiedCreatorShape
} 
:IdentifiedCreatorShape @:NamedCreatorShape OR @:LinkedCreatorShape
:NamedCreatorShape { so:name xsd:string }
:LinkedCreatorShape { so:url so:URL } 
:PersonShape { a [so:Person] }
:OrganizationShape { a [so:Organization] }
```

...

This is general enough that I expect similar structures would be relevant for DCAT too.

Nearby: [Python](https://github.com/hsolbrig/PyShEx) and Javascript [libraries](https://www.npmjs.com/package/shex). Also some [new docs](https://rawgit.com/shexSpec/primer/on-shape-expression/index.html).

I remain interested in both ShEx and SHACL for capturing data patterns understood by search engines like Google (and the others). One part of this will be figuring out how consuming applications can associate fine-grained information pointing into human-friendly documentation, guidance, dedicated . validation tools etc.

/cc @ericprud @tombaker @dr-shorthair @andrea-perego

**Comment by danbri** [comment]
Trying to migrate this to DCAT, here is a simple RDFa example we've used in Google's developer docs to indicate one pattern of using DCAT 1.0 that we can in some sense "understand" (update - I think the rdfa is a bit wrong; eric cleans it up a bit below))

``` html
<article about="/node/1234" typeof="dcat:Dataset">
  <dl>
    <dt>Name:</dt>
    <dd> property="dc:title">ACME Inc Cash flow data</dd>
    <dt>Description:</dt>
    <dd property="dc:description">Financial Statements - Consolidated Statement of Cash Flows</dd>
    <dt>Category:</dt>
    <dd rel="dc:subject">Financial</dd>
    <dt class="field-label">Downloads:</dt>
    <dd>
      <ul>
        <li rel="dcat:distribution" resource="/sites/default/files/Consolidated_Statement_of_Cash_Flows_en.csv" property="dcat:mediaType" content="text/csv">
          <a href="files/Consolidated_Statement_of_Cash_Flows_en.csv">Consolidated_Statement_of_Cash_Flows_en.csv</a>
        </li>
        <li rel="dcat:distribution" resource="/sites/default/files/Consolidated_Statement_of_Cash_Flows_en.xls" property="dcat:mediaType" content="application/vnd.ms-excel">
          <a href="files/Consolidated_Statement_of_Cash_Flows_en.xls">Consolidated_Statement_of_Cash_Flows_en.xls</a>
        </li>
        <li rel="dcat:distribution" resource="/sites/default/files/consolidated_statement_of_cash_flows_en.xml" property="dcat:mediaType" content="application/xml">
          <a href="files/consolidated_statement_of_cash_flows_en.xml">consolidated_statement_of_cash_flows_en.xml</a>
        </li>
      </ul>
    </dd>
  </dl>
</article>
```

Let's see that as triples, well Turtle, thanks to @iherman's RDFa 1.1 distiller:

``` 
@prefix :      <http://example.org/> .
@prefix dcat:  <http://www.w3.org/ns/dcat#> .
@prefix dc:    <http://purl.org/dc/terms/> .

:ds1    a                  dcat:Dataset ;
        dc:description     "Financial Statements - Consolidated Statement of Cash Flows" ;
        dcat:distribution  <file:///sites/default/files/Consolidated_Statement_of_Cash_Flows_en.csv> , <file:///sites/default/files/Consolidated_Statement_of_Cash_Flows_en.xls> , <file:///sites/default/files/consolidated_statement_of_cash_flows_en.xml> ;
        dcat:mediaType     "application/vnd.ms-excel" , "application/xml" , "text/csv" .

```

Here are N-Triples:

*  <http://example.org/eg1/node/1234> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/dcat#Dataset> .
*  <http://example.org/eg1/node/1234> <http://purl.org/dc/terms/description> "Financial Statements - Consolidated Statement of Cash Flows" .
* <http://example.org/eg1/node/1234> <http://www.w3.org/ns/dcat#mediaType> "application/vnd.ms-excel" .
* <http://example.org/eg1/node/1234> <http://www.w3.org/ns/dcat#mediaType> "application/xml" .
* <http://example.org/eg1/node/1234> <http://www.w3.org/ns/dcat#mediaType> "text/csv" .
 * <http://example.org/eg1/#/node/1234> <http://www.w3.org/ns/dcat#distribution> 
 * <http://example.org/eg1/sites/default/files/Consolidated_Statement_of_Cash_Flows_en.csv> .
 * <http://example.org/eg1/node/1234> <http://www.w3.org/ns/dcat#distribution> </sites/default/files/consolidated_statement_of_cash_flows_en.xml> .
 * <http://example.org/eg1/node/1234> <http://www.w3.org/ns/dcat#distribution> </sites/default/files/Consolidated_Statement_of_Cash_Flows_en.xls> .
 
How does this compare to the ShEx above?

Can we mutate that Turtle into ShEx, taking account also of the [shacl draft](https://github.com/SEMICeu/dcat-ap_shacl/blob/master/shacl/dcat-ap.shapes.ttl) ?

I've added a dcat:, a foaf: and a dc: prefix declaration, and removed schema.org's. These are all just a sketch for now.

```
PREFIX :       <http://example.org/>
PREFIX dcat: <http://www.w3.org/ns/dcat> 
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

:DataSetShape {
 dc:title . ;  
 dc:description .  ; 
 dcat:accessURL . ;
 dcat:distribution . ;
 dcat:mediaType . ;
 dc:publisher (@:PersonShape OR @:OrganizationShape) AND 
            @:IdentifiedCreatorShape
} 
:IdentifiedCreatorShape @:NamedCreatorShape OR @:LinkedCreatorShape
:NamedCreatorShape { foaf:name xsd:string }
:LinkedCreatorShape { foaf:homepage . } 
:PersonShape { a [foaf:Person] }
:OrganizationShape { a [foaf:Organization] }
```

Does this give us something we can play with? It doesn't matter for now if the example Turtle doesn't meet the expressed shapes, that's pretty much the point of trying to do this... 

I got this far:

https://goo.gl/GVXgdv

**Comment by danbri** [comment]
@ericprud cleaned this up a bit (and I noticed that the original RDFa/Turtle was badly structured, this captures the intent.

* See new version in [RDFShape](https://tinyurl.com/yddutxyd), [shex.js](https://tinyurl.com/y7n7dzr4)

ShEx is:

```
PREFIX :       <http://example.org/>
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

:DataSetShape {
  a [dcat:Dataset] ;
  dc:title LITERAL ? ;
  dc:description LITERAL ; 
  dcat:accessURL IRI ? ;
  dcat:distribution IRI @:DistributionShape + ;
  dc:publisher (@:PersonShape OR @:OrganizationShape) AND 
                @:IdentifiedCreatorShape ?
}

:DistributionShape {
  dcat:mediaType /^(application|text)\/[a-z.-]+$/ + ;
}

:IdentifiedCreatorShape @:NamedCreatorShape OR @:LinkedCreatorShape
:NamedCreatorShape { foaf:name xsd:string }
:LinkedCreatorShape { foaf:homepage . } 
:PersonShape { a [foaf:Person] }
:OrganizationShape { a [foaf:Organization] }
```

Turtle is:

```
@prefix :      <http://example.org/> .
@prefix dcat:  <http://www.w3.org/ns/dcat#> .
@prefix dc:    <http://purl.org/dc/terms/> .
PREFIX cash:   <file:///sites/default/files/Consolidated_Statement_of_Cash_Flows_en.>

:ds1    a                  dcat:Dataset ;
        dc:description     "Financial Statements - Consolidated Statement of Cash Flows" ;
        dcat:distribution  cash:csv , cash:xls , cash:xml .
cash:csv dcat:mediaType "text/csv" .
cash:xls dcat:mediaType "application/vnd.ms-excel" .
cash:xml dcat:mediaType "application/xml" .
```

**Comment by danbri** [comment]
I've fixed the RDFa (and will fix at Google developer docs in due source),

```
<article about="/node/1234" typeof="dcat:Dataset">
  <dl>
    <dt>Name:</dt>
    <dd> property="dc:title">ACME Inc Cash flow data</dd>
    <dt>Description:</dt>
    <dd property="dc:description">Financial Statements - Consolidated Statement of Cash Flows</dd>
    <dt>Category:</dt>
    <dd rel="dc:subject">Financial</dd>
    <dt class="field-label">Downloads:</dt>
    <dd>
      <ul>
        <li>
          <a rel="dcat:distribution" href="Consolidated_Statement_of_Cash_Flows_en.csv"><span property="dcat:mediaType" content="text/csv" >Consolidated_Statement_of_Cash_Flows_en.csv</span></a>
        </li>
       <li>
          <a rel="dcat:distribution"  href="files/Consolidated_Statement_of_Cash_Flows_en.xls"><span property="dcat:mediaType" content="application/vnd.ms-excel">Consolidated_Statement_of_Cash_Flows_en.xls</span></a>
        </li>
        <li>
          <a rel="dcat:distribution"  href="files/consolidated_statement_of_cash_flows_en.xml"><span property="dcat:mediaType" content="application/xml">consolidated_statement_of_cash_flows_en.xml</span></a>
        </li>
      </ul>
    </dd>
  </dl>
</article>
```

**Comment by VladimirAlexiev** [comment]
Some benefits of shex 
- is a lot more compact. Unless you use the proposed shaclc, shacl is 5-10x wordier
- supportts recursive shapes
- has an extensive test suite

**Comment by addragan** [comment]
Issue proposed to be closed as currently, we are not looking into developing new representations for DCAT-AP but focus on expanding the SHACL representation which is aligned with the work on the DCAT-AP Test Bed Validator activity.
