### ISSUE TITLE
inverse Path constraint

### ISSUE THREAD

**Issue by ghost** [SEMICeu/dcat-ap_shacl#34]
`:MandatoryDataset
  rdf:type sh:NodeShape ;
  rdfs:comment "Mandatory dataset " ;
  rdfs:label "Mandatory dataset" ;
  sh:property [
      sh:minCount 1 ;
      sh:path [
          sh:inversePath rdf:type ;
        ] ;
    ] ;
  sh:targetNode "dcat:Dataset" ;
.`

The targetNode should not be a string.

**Comment by costezki** [comment]
Indeed, thank you for pointing that out. 
Fixed now.
