### ISSUE TITLE
test suite

### ISSUE THREAD

**Issue by ghost** [SEMICeu/dcat-ap_shacl#35]
Are there plans top develop a test suite?

**Comment by costezki** [comment]
Not yet but we consider this issue as an open request for adding a test suite for the DCAT-AP.

**Comment by addragan** [comment]
Proposed resolution: A solution is under development under ISA Test Bed – DCAT-AP Validator.

**Comment by bertvannuffelen** [comment]
see https://www.itb.ec.europa.eu/shacl/dcat-ap/upload.
