### ISSUE TITLE
why sh:class rdfs:Resource ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/dcat-ap_shacl#36]
A few shapes in dcat-ap.shapes.ttl contain the rule "sh:class rdfs:Resource"
Which seems odd, since rdfs:Resource is really anything...

Can this just be ignored / removed ?
Or replaced with sh:NodeKind sh:IRIOrLiteral (assuming that's what the rule is about ?)

**Comment by costezki** [comment]
Hi Bart, 
thank you for pointing this out. 

I corrected the entries.
