### ISSUE TITLE
dcat:mediaType value constraint

### ISSUE THREAD

**Issue by costezki** [SEMICeu/dcat-ap_shacl#4]
To my knowledge IANA does not provide a list of URIs for mime type. Is there an alternative to that? 
Otherwise cannot set a validation constraint on dcat:mediaType controlled vocabulary

**Comment by makxdekkers** [comment]
There is a list on https://www.iana.org/assignments/media-types/media-types.xhtml, e.g. there is a URI for https://www.iana.org/assignments/media-types/application/rdf+xml, but not all MIME types have such a URI.
