### ISSUE TITLE
Mandatory class test

### ISSUE THREAD

**Issue by costezki** [SEMICeu/dcat-ap_shacl#6]
Shall we check for presence of mandatory class instances in the data-set and if so which ones?

Currently there are three shapes :MandatoryAgent, :MandatoryCatalog and :MandatoryDataset that are checking for presence of at least one instances of foaf:Agent, dcat:Catalog and dcat:Dataset. 

Shall we keep or remove them? 

PS: this leads me to a broader question: when we validate a data-set want do we want to verify? 

* that it is conform the shape file or 
* that it is not violating a set of shapes

**Comment by makxdekkers** [comment]
From my perspective, I do not really know what is gained by checking mandatory classes so I would vote for removing the shapes.
I am not sure what the difference between the two choices is. Isn't 'conforming' the same as 'not violating'?

**Comment by costezki** [comment]
What I meant is the following: 
in case of an incomplete DCAT description (e.g. only a "correct" catalog instance is available): 
* it will be not be violating the the AP (because only Catalog shape will be triggered fro validation)
* at the same time it will not be totally conform to AP because it is incomplete (thus a violation shall be raised stating the incompleteness). 

I would also vote in favor of "reactive" approach, to only check whether the provided data does not violate the AP without imposing some minimal constraints on their completeness (i.e. request that there is at least one Dataset instance in addition to the provided Catalog instance)

Already submitted a modification where I split the MandatoryClass checks into another module.
