### ISSUE TITLE
Readability of the RDF/XML file

### ISSUE THREAD

**Issue by costezki** [SEMICeu/dcat-ap_shacl#9]
* The file would benefit from commentary, at least to indicate the various sections. Maybe even an index to show where the various sections begin?
* It could be good to organise lists alphabetically, e.g. the list of namespaces at the start. Also, there is no obvious order in the properties in the description of the vocabulary in lines 42-168; maybe they could be grouped together alphabetically per namespace?
* It’s a bit hard to figure out, but it seems that the class shape of the Distribution is described inside the property shape for dataset-sample. The class shape for Dataset starts at line 208 and ends at line 626, Distribution from line 237 to 424, CatalogRecord 627-692 and Catalog 639-818. Should the class shape of Distribution not be on the same hierarchical level as the shapes for Dataset, Catalog and CatalogRecord?
* The property shapes under the classes do not seem to be ordered in any way. It could be useful to do the mandatory ones first, then the recommended ones and the optional ones last.

**Comment by akuckartz** [comment]
RDF and XML by themselves are nice. But RDF/XML is ugly. Please use Turtle or a similar format.

**Comment by addragan** [comment]
Proposed resolution: It is proposed to enhance to code with the recommendations made on points #1 to #4.

**Comment by akuckartz** [comment]
What is the target audience of that XML file?

**Comment by bertvannuffelen** [comment]
closed because of archiving
